[package]
name = "mdsvexrs-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
wee_alloc = []

[dependencies]
wasm-bindgen = "*"
mdsvexrs = { path = "../..", default-features = false, features = ["fancy"]}